<a href="https://colab.research.google.com/github/xxziris/BS6207/blob/main/BS6207_Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# BS6207 Assignment 1

Xinxin <br>
Mar/2021

----

Given a fully connected Neural Network as follows: <br>
1. Input (x1,x2): 2 nodes
2. First hidden layer: 10 nodes, with weights (w) and bias (b), sigmoid activation function
3. Second hidden layer: 10 nodes, with weights (w) and bias (b), sigmoid activation function
4. Output (predict): 1 node

__Requirements:__ <br>
1. Implement this neural network in pytorch
2. Generate the input date (x1,x2) \in [0,1] drawn from a uniform random distribution
3. Generate the labels y = (x1*x1+x2*x2)/2
4. Implement a loss function L = (predict-y)^2
5. Use batch size of 1, that means feed data one point at a time into network and compute the loss. Do one time forward propagation with one data point.
6. Compute the gradients using pytorch autograd:
    - dL/dw, dL/db
    - Print these values into a text file: torch_autograd.dat
7. Implement the forward propagation and backpropagation algorithm from scratch, without using pytorch autograd, compute the gradients using your implementation
    - dL/dw, dL/db
    - Print these values into a text file: my_autograd.dat
8. Compare the two files torch_autograd.dat and my_autograd.dat and show that they give
the same values up to numerical precision errors

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import random

In [2]:
# 1. implement the neural network in pytorch
class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.fc1 = nn.Linear(2, 10)
    self.fc2 = nn.Linear(10, 10)
    self.fc3 = nn.Linear(10, 1)

  def forward(self, x):
    x = torch.sigmoid(self.fc1(x))
    x = torch.sigmoid(self.fc2(x))
    return self.fc3(x)

net = Net()
print(net)

Net(
  (fc1): Linear(in_features=2, out_features=10, bias=True)
  (fc2): Linear(in_features=10, out_features=10, bias=True)
  (fc3): Linear(in_features=10, out_features=1, bias=True)
)


In [3]:
random.seed(127)
# 2. generate input data x1 x2 from uniform random distribution of [0,1]
input = torch.rand(1,2, requires_grad = False)

# 3. generate the labels of input data
y = (input[0][0]**2 + input[0][1]**2)/2

In [4]:
# 4. define loss function
def my_loss(output, target):
  loss = (output - target)**2
  return loss

In [5]:
# 5. One time forward propagation with one data point
y_pred = net(input)

In [6]:
# 6. compute dL/dw, dL/db using pytorch autograd
loss = my_loss(y_pred, y)
loss.backward(retain_graph = True)


In [7]:
loss

tensor([[0.1411]], grad_fn=<PowBackward0>)

In [8]:
# print dL/dw to check
print('dL/dw3 = ', net.fc3.weight.grad)
print('dL/dw2 = ', net.fc2.weight.grad)
print('dL/dw1 = ', net.fc1.weight.grad)

dL/dw3 =  tensor([[-0.3391, -0.3071, -0.3031, -0.3271, -0.3050, -0.4498, -0.4268, -0.3326,
         -0.3236, -0.2691]])
dL/dw2 =  tensor([[-0.0027, -0.0027, -0.0030, -0.0027, -0.0036, -0.0031, -0.0016, -0.0040,
         -0.0026, -0.0017],
        [-0.0203, -0.0208, -0.0232, -0.0203, -0.0273, -0.0233, -0.0121, -0.0302,
         -0.0201, -0.0129],
        [ 0.0042,  0.0043,  0.0048,  0.0042,  0.0056,  0.0048,  0.0025,  0.0062,
          0.0041,  0.0027],
        [-0.0014, -0.0015, -0.0016, -0.0014, -0.0019, -0.0016, -0.0009, -0.0021,
         -0.0014, -0.0009],
        [-0.0059, -0.0060, -0.0067, -0.0059, -0.0079, -0.0067, -0.0035, -0.0087,
         -0.0058, -0.0037],
        [ 0.0213,  0.0218,  0.0243,  0.0213,  0.0286,  0.0245,  0.0127,  0.0317,
          0.0211,  0.0135],
        [ 0.0130,  0.0133,  0.0149,  0.0130,  0.0175,  0.0150,  0.0078,  0.0194,
          0.0129,  0.0083],
        [-0.0113, -0.0116, -0.0129, -0.0113, -0.0152, -0.0130, -0.0067, -0.0168,
         -0.0112, -0.0072]

In [9]:
# print dL/db to check
print('dL/db3 = ', net.fc3.bias.grad)
print('dL/db2 = ', net.fc2.bias.grad)
print('dL/db1 = ', net.fc1.bias.grad)

dL/db3 =  tensor([-0.7513])
dL/db2 =  tensor([-0.0063, -0.0481,  0.0099, -0.0034, -0.0139,  0.0505,  0.0309, -0.0268,
        -0.0276,  0.0502])
dL/db1 =  tensor([ 0.0043,  0.0006,  0.0106,  0.0027, -0.0010, -0.0052, -0.0023,  0.0035,
        -0.0011,  0.0054])


In [10]:
# write the gradiet to torch_autograd.dat
with open('/content/drive/MyDrive/Colab Notebooks/BS6207/Assignment1/torch_autograd.dat',"w") as file:
  file.write('\ndLdw3\n')
  file.write(np.array2string(net.fc3.weight.grad.data.numpy(), precision = 7, separator = ','))
  file.write('\ndLdw2\n')
  file.write(np.array2string(net.fc2.weight.grad.data.numpy(), precision = 7, separator = ','))
  file.write('\ndLdw1\n')
  file.write(np.array2string(net.fc1.weight.grad.data.numpy(), precision = 7, separator = ','))
  file.write('\ndLdb3\n')
  file.write(np.array2string(net.fc3.bias.grad.data.numpy(), precision = 7, separator = ','))
  file.write('\ndLdb2\n')
  file.write(np.array2string(net.fc2.bias.grad.data.numpy(), precision = 7, separator = ','))
  file.write('\ndLdb1\n')
  file.write(np.array2string(net.fc1.bias.grad.data.numpy(), precision = 7, separator = ','))


In [11]:
# 7. Implement forward propagation and backward propagation from scratch
# get the same weight and bias from the model above
w1 = net.fc1.weight
w2 = net.fc2.weight
w3 = net.fc3.weight

b1 = net.fc1.bias
b2 = net.fc2.bias
b3 = net.fc3.bias

In [12]:
# define the sigmoid activation function from scratch
def sigmoid(input):
  return 1/(1 + torch.exp(-input))

In [13]:
# define function for derivative of sigmoid
def sigmoid_der(input):
  s = sigmoid(input)
  return torch.transpose(s*(1-s), 0, 1)

In [14]:
# forward propagation

# first layer
z1 = torch.mm(input, torch.transpose(w1,0,1)) + b1
h1 = sigmoid(z1)
# second layer
z2 = torch.mm(h1, torch.transpose(w2,0,1)) + b2
h2 = sigmoid(z2)
# output
h3 = torch.mm(h2, torch.transpose(w3,0,1)) + b3

In [15]:
# backward propagation
loss_2 = my_loss(h3, y)
loss_2 # same as the loss from the model above

tensor([[0.1411]], grad_fn=<PowBackward0>)

In [16]:
# check if the output is the same as the model above
print(h3, y_pred)

tensor([[0.1632]], grad_fn=<AddBackward0>) tensor([[0.1632]], grad_fn=<AddmmBackward>)


In [17]:
# calculate dL/dw3
dL_dw3 = 2 * (h3 - y) * h2
dL_dw3

tensor([[-0.3391, -0.3071, -0.3031, -0.3271, -0.3050, -0.4498, -0.4268, -0.3326,
         -0.3236, -0.2691]], grad_fn=<MulBackward0>)

In [18]:
# calculate dL/dw2
dL_dw2 =  2 * (h3 - y) * torch.transpose(w3, 0, 1) @ h1 * sigmoid_der(z2)
dL_dw2

tensor([[-0.0027, -0.0027, -0.0030, -0.0027, -0.0036, -0.0031, -0.0016, -0.0040,
         -0.0026, -0.0017],
        [-0.0203, -0.0208, -0.0232, -0.0203, -0.0273, -0.0233, -0.0121, -0.0302,
         -0.0201, -0.0129],
        [ 0.0042,  0.0043,  0.0048,  0.0042,  0.0056,  0.0048,  0.0025,  0.0062,
          0.0041,  0.0027],
        [-0.0014, -0.0015, -0.0016, -0.0014, -0.0019, -0.0016, -0.0009, -0.0021,
         -0.0014, -0.0009],
        [-0.0059, -0.0060, -0.0067, -0.0059, -0.0079, -0.0067, -0.0035, -0.0087,
         -0.0058, -0.0037],
        [ 0.0213,  0.0218,  0.0243,  0.0213,  0.0286,  0.0245,  0.0127,  0.0317,
          0.0211,  0.0135],
        [ 0.0130,  0.0133,  0.0149,  0.0130,  0.0175,  0.0150,  0.0078,  0.0194,
          0.0129,  0.0083],
        [-0.0113, -0.0116, -0.0129, -0.0113, -0.0152, -0.0130, -0.0067, -0.0168,
         -0.0112, -0.0072],
        [-0.0117, -0.0119, -0.0133, -0.0117, -0.0157, -0.0134, -0.0069, -0.0173,
         -0.0115, -0.0074],
        [ 0.0212,  

In [19]:
# calculate dL/dw1
dL_dw1 = torch.transpose(torch.transpose(2 * (h3 - y) * torch.transpose(w3, 0, 1) * sigmoid_der(z2) , 0,1 ) @ w2, 0,1) @ input * sigmoid_der(z1)
dL_dw1

tensor([[ 0.0014,  0.0042],
        [ 0.0002,  0.0006],
        [ 0.0034,  0.0104],
        [ 0.0009,  0.0027],
        [-0.0003, -0.0010],
        [-0.0017, -0.0051],
        [-0.0007, -0.0023],
        [ 0.0011,  0.0035],
        [-0.0003, -0.0011],
        [ 0.0017,  0.0053]], grad_fn=<MulBackward0>)

In [20]:
# calculate dL/db3
dL_db3 = 2 * (h3 - y)
dL_db3

tensor([[-0.7513]], grad_fn=<MulBackward0>)

In [21]:
# calculate dL/db2
dL_db2 = torch.transpose(2 * (h3 - y) * torch.transpose(w3, 0, 1) * sigmoid_der(z2), 0, 1)
dL_db2

tensor([[-0.0063, -0.0481,  0.0099, -0.0034, -0.0139,  0.0505,  0.0309, -0.0268,
         -0.0276,  0.0502]], grad_fn=<TransposeBackward0>)

In [22]:
# calculate dL/db1
dL_db1 = torch.transpose(torch.transpose(torch.transpose(2 * (h3 - y) * torch.transpose(w3, 0, 1) * sigmoid_der(z2), 0, 1) @ w2, 0, 1) * sigmoid_der(z1), 0, 1)
dL_db1

tensor([[ 0.0043,  0.0006,  0.0106,  0.0027, -0.0010, -0.0052, -0.0023,  0.0035,
         -0.0011,  0.0054]], grad_fn=<TransposeBackward0>)

In [23]:
# output the calculated gradient to my_autograd.dat
with open('/content/drive/MyDrive/Colab Notebooks/BS6207/Assignment1/my_autograd.dat',"w") as file:
  file.write('\ndLdw3\n')
  file.write(np.array2string(dL_dw3.data.numpy(), precision = 7, separator = ','))
  file.write('\ndLdw2\n')
  file.write(np.array2string(dL_dw2.data.numpy(), precision = 7, separator = ','))
  file.write('\ndLdw1\n')
  file.write(np.array2string(dL_dw1.data.numpy(), precision = 7, separator = ','))
  file.write('\ndLdb3\n')
  file.write(np.array2string(dL_db3.data.numpy()[0], precision = 7, separator = ','))
  file.write('\ndLdb2\n')
  file.write(np.array2string(dL_db2.data.numpy()[0], precision = 7, separator = ','))
  file.write('\ndLdb1\n')
  file.write(np.array2string(dL_db1.data.numpy()[0], precision = 7, separator = ','))

By comparing the two output files, the loss function has the same gradient against weights and biases from the pytorch model and the self-constructed model.